version: 2

sources:
  - name: conformed
    database: raw_statsnfacts
    schema: conformed

    tables:
      - name: DateDimension
        columns: 
          - name: DateKey
            tests:
              - unique

  - name: chinook
    database: raw_statsnfacts
    schema: chinook

    tables:
      - name: Customers
        columns:
          - name: CustomerId
            tests:
              - unique